### ISSUE TITLE
windows: hotkeys show as macos command key instead of control

### ISSUE THREAD

**Issue by Patrity** [february-labs/devgpt-releases#1]
![image](https://github.com/february-labs/devgpt-releases/assets/42813882/973fe52c-a54e-47ce-b7c4-4f1dd560e32b)

**Comment by tom-lewis-code** [comment]
Hey Patrity, thank you for raising the issue feedback!

I've added these, and it will be in our next release.
![image](https://github.com/february-labs/devgpt-releases/assets/73704914/baf2e7c2-8b9b-48df-a9eb-f7e15ba901fd)

Thanks again,
Tom.
