### ISSUE TITLE
Issue: Code Gen failing for a few users

### ISSUE THREAD

**Issue by tom-lewis-code** [february-labs/devgpt-releases#11]
Reported by: Fatih Kacar, Ian, Bluejacket, john0x

**Comment by tom-lewis-code** [comment]
Some understood causes so far are size of repo (using an especially large repo). This isn't due to build files, not modules (other large build files in other languages) as we filter them out. Any other abnormalities in repos: please comment!

**Comment by fkacar** [comment]
Our repo has 2200 Files and 137000 lines of code. Typescript react project. This prompt worked outcome is too bad:

`
create a fake-db file for admins list mock data`

After that, all tasks failed.

**Comment by ggottemo** [comment]
I believe you're on the right track with file count. It works on a barebones python fastapi project or next.js starter with only a few files. But if I try it in a c# repo with the "blazor server app" template (has considerably more files), then it fails
