### ISSUE TITLE
Bug: App cannot be used anymore once an update has been published

### ISSUE THREAD

**Issue by rocketinventor** [february-labs/devgpt-releases#13]
Whenever there is a new minor update, the app locks up and denies app usage until that new update has been installed. There is no opt-out for the new version, and no use-it-while-it-updates feature, either.

A simple "X" button to close the update notice (and go back to the main screen) would provide much better usability.

Not everyone has a super-speed internet connection with unlimited data usage available to them - updating the app uses up to a half gig of bandwidth. Not everyone wants to be bothered all the time. Also, installing the app takes time - not great when you just installed the newest version of the app yesterday and now cannot use it anymore (especially when you were just about to use it).

There is no reason why the app usage should be blocked every single time that there is a new minor release until that release has been downloaded and installed. In general terms, no other app works this way.

![image](https://github.com/february-labs/devgpt-releases/assets/6473114/a5826cce-304e-4ad6-8f06-08d66d9529d0)

**Comment by ash-lewis** [comment]
Valid issue @rocketinventor, we're going to try and get this patched in our next update. Thank you for the feedback!

**Comment by tom-lewis-code** [comment]
This issue was resolved in version 1.0.7.
