### ISSUE TITLE
Excluded files and folders does not seem to work

### ISSUE THREAD

**Issue by derick-dsouza** [february-labs/devgpt-releases#15]
![DevGPT_wck9taT77V](https://github.com/february-labs/devgpt-releases/assets/74296942/975bf413-f6bf-4813-9bf3-e109915c8892)

See attachment: I used the defaults as node_modules, .git, .vscode, dist were the folders I want excluded. I tried tweaking the pattern to see if I could get it to work but it somehow did not work

Default: /node_modules/

I tried the following, none of which worked:
node_modules/
./node_modules/
/node_modules/*
/node_modules/**/

Another related question: Does the exclusion pattern work only on the root folder or does it apply to sub folders as well?

**Comment by tom-lewis-code** [comment]
Hey Derick, Thank you for your report! I'll look into this right away.

We don't have any other active reported issues with the excluded files and folders yet but I'll keep checking.

**Comment by derick-dsouza** [comment]
Thanks Tom, let me know if you cannot reproduce this issue. I could try it again and share some information if required. Its a show stopper for me right now and I am keen to continue my evaluation of DevGPT.

     Kind Regards,

[cid:332f56e4-b9f8-4991-b355-b0c18dab3d3c]

[Title: LinkedIn - Description: image of LinkedIn icon]<https://www.linkedin.com/in/derickdsouza/> [Title: Facebook - Description: image of Facebook icon] <https://www.facebook.com/derick.dsouza>  [Title: Twitter - Description: image of Twitter icon] <https://twitter.com/dsouzaderick>
Derick Dsouza
Head of Development & Delivery

[signature_64823905]
Email: ***@***.******@***.***>
Mobile: +91 9766257263
www.whitelabeles.com<http://www.whitelabeles.com>




________________________________

**Comment by derick-dsouza** [comment]
Fixed in v1.0.6
