### ISSUE TITLE
windows: window control missing

### ISSUE THREAD

**Issue by Patrity** [february-labs/devgpt-releases#2]
Minimize, maximize, and close buttons do not exist on the installed windows version:

![image](https://github.com/february-labs/devgpt-releases/assets/42813882/1a4aa874-fbf3-428c-b62d-80df712eba4d)

**Comment by tom-lewis-code** [comment]
Hey Patrity, 

Super feedback again, really appreciate it. I've added these and they will be added in our next release.
![image](https://github.com/february-labs/devgpt-releases/assets/73704914/1f6aa47b-4613-4178-9ace-e66f560aeadb)
