### ISSUE TITLE
suggestion: folder select on repository settings

### ISSUE THREAD

**Issue by Patrity** [february-labs/devgpt-releases#3]
Instead of requiring the user to manually type or copy/paste their folder path, add a folder selection button.
The "Cancel" button is also redundant, given that there is also an "X" close button in the top-right.
![image](https://github.com/february-labs/devgpt-releases/assets/42813882/d7fedac8-93b2-49bc-a2af-ab5d3f38987b)

Here is an example from the Github Desktop app:
![image](https://github.com/february-labs/devgpt-releases/assets/42813882/c3ce8546-1976-43b8-b8b9-d388d91e050b)

Selecting the "choose" button opens this window allowing you to select a folder:
![image](https://github.com/february-labs/devgpt-releases/assets/42813882/caa0231d-3e09-457d-a835-64b3e97aa8f1)

**Comment by Patrity** [comment]
Another flaw with this setup; I do not see a way to designate a folder that is outside of the user folder, for example if the user develops on another drive, such as D:/ or a network drive.

**Comment by tom-lewis-code** [comment]
Hey Patrity,

The flaw about working outside of the main drive is totally correct. We've seen some users having trouble as they work outside of the C:\ drive. I'll see how we can improve that!

In the meantime, I love the suggestion of a select folder option. Way more elegant and straightforward. Will be in our next release.

![image](https://github.com/february-labs/devgpt-releases/assets/73704914/737d5701-d2e2-41eb-81a3-f6d747b7a1cd)

Thanks again!
