### ISSUE TITLE
[bug] prompted to move blocks of rust code, ai did everything else but that

### ISSUE THREAD

**Issue by RobertasJ** [february-labs/devgpt-releases#37]
i dont know how to explain it, but it managed to change everything but what i asked it for. i think you aren't including a hefty chunk of the information provided.

follow up with any questions if needed.

**Comment by HRA42** [comment]
Hi @RobertasJ :)

The devs pushed an update yesterday. Could you update and check if the issue still persists?

**Comment by RobertasJ** [comment]
Its fixed dw
