### ISSUE TITLE
suggestion: chatbot and task confirmation

### ISSUE THREAD

**Issue by Patrity** [february-labs/devgpt-releases#4]
When creating a new task, there is no way to just designate that you want to use the bot as a standard chat bot like a ChatGPT replacement.
I can see benefit to wanting to use DevGPT as to just get suggestions, then another user interaction, to convert that suggestion or response to a task.
Furthermore, when starting a task, the bot should develop the solution and there should be some form of user confirmation before the bot just freely modifies your codebase. Currently, when a task is started, there is no further user interaction until the code is written and the task is complete.

**Comment by tom-lewis-code** [comment]
In our newest release this features heavily. Thank you for your suggestion @Patrity! I hope we've managed to capture your idea as you imagined it.
