### ISSUE TITLE
cant send follow up message

### ISSUE THREAD

**Issue by gavishap** [february-labs/devgpt-releases#47]
cant send follow up message after paying 15 bucks

**Comment by HRA42** [comment]
Could you please log out and restart the app, after you log in again it should work.

**Comment by ash-lewis** [comment]
Hi @gavishap this should now be resolved in v1.1.1, can you please try again for me and if it still fails raise another bug ticket? Thank you!

**Comment by gavishap** [comment]
Please undo my membership. Thank you
