### ISSUE TITLE
[BUG] Send button in follow-up not working

### ISSUE THREAD

**Issue by ZenfadeCOM** [february-labs/devgpt-releases#48]
The send button for the follow-up prompt seems broken.
Pressing Enter still works.

**Comment by HRA42** [comment]
Hi @ZenfadeCOM :)

The devs released a new version today. Could you update and tell us if the button is still broken for you? :)

https://github.com/february-labs/devgpt-releases/releases

**Comment by ash-lewis** [comment]
Can you please try this again in v1.1.1 @ZenfadeCOM ? Thank you
