### ISSUE TITLE
undefined paste

### ISSUE THREAD

**Issue by timothymoniaga** [february-labs/devgpt-releases#49]
when copying code that was generated from devgpt it resulted in `undefined` being pasted instead of the code. This only occurs when clicking the copy code on the top right of the code block, when selecting and copying the code manually it works fine.

**Comment by HRA42** [comment]
Hi @timothymoniaga :)

Could you please download the latest version and try to copy again? :

**Comment by ash-lewis** [comment]
Thank you for reporting @timothymoniaga , this has been solved in v1.1.1!
