### ISSUE TITLE
Can't remove last item in the "Excluded files from training"

### ISSUE THREAD

**Issue by RiCatarino** [february-labs/devgpt-releases#51]
When trying to delete, by pressing the "x" button, the last item added to the list, nothing happens, to delete it, i must add another item for it not to be the last.

This is happening on M1 Macbook Pro.

https://github.com/february-labs/devgpt-releases/assets/29524722/40a58562-6383-4197-82e9-a1374ffb1096

**Comment by HRA42** [comment]
Hi @RiCatarino :)

I checked with the windows version and it seems to be fixed in the latest version. Could you make sure you have the latest version (1.1.0 - https://github.com/february-labs/devgpt-releases/releases/tag/1.1.0) and check if this issue is still present for you? :)

**Comment by RiCatarino** [comment]
Hi @HRA42, with the unlocked features released in version 1.0.9, this does not appear, although i believe the issues is fixed. Thank you.
