### ISSUE TITLE
Invalid API key

### ISSUE THREAD

**Issue by thabalija** [february-labs/devgpt-releases#53]
An invalid API key error comes up upon registration.

The issue occurs on the latest macOS version of the app (1.0.8), running on Ventura 13.5.2.

![Screenshot 2023-09-11 at 07 23 35](https://github.com/february-labs/devgpt-releases/assets/34454495/22c8e276-f403-4fd5-a363-70d289a8fe20)

**Comment by vohuynh19** [comment]
Same problem! Any help?

**Comment by hrasekj** [comment]
Looks like its not OS issue, i got the same error on Ubuntu.

**Comment by themazim** [comment]
Same issue for me.

**Comment by JulianStremel** [comment]
Same on Windows 11

**Comment by tom-lewis-code** [comment]
hey @themazim @hrasekj @thabalija @vohuynh19 @ardevpk, thank you all for your report! 

We're currently handling an outage and will be back online within a few hours. For instant updates you can join our discord! :) I'll also try to remember to update here when all is operational again

**Comment by HRA42** [comment]
@themazim @hrasekj @thabalija @vohuynh19 @ardevpk The devs released a new version!

You can download from the release page: https://github.com/february-labs/devgpt-releases/releases

**Comment by thabalija** [comment]
Thank you, it works now!
