### ISSUE TITLE
Teck Stack

### ISSUE THREAD

**Issue by thorrak** [february-labs/devgpt-releases#55]
Pretty sure this is supposed to be "Tech":

<img width="198" alt="Screenshot 2023-09-11 at 10 03 37 AM" src="https://github.com/february-labs/devgpt-releases/assets/2457900/8bf6b40a-8b2e-4d68-9d70-2acc5ac0c9f3">

**Comment by HRA42** [comment]
@tom-lewis-code can you confirm if thats not wanted?

**Comment by tom-lewis-code** [comment]
hey @thorrak and @HRA42, Oh my god. I had to read this issue 4 times to actually realise it's a mistype. This section is being removed in an upcoming update and replace, but we will get this changed. 

Can confirm: active issue and unresolved

**Comment by ash-lewis** [comment]
Fixed in version 1.1.1!
