### ISSUE TITLE
No output after answering the questions.

### ISSUE THREAD

**Issue by PsychosisMNY** [february-labs/devgpt-releases#69]
New user, followed the instructions, no getting any output from DevGPT after answering the questions on a new task.
Also I noticed the website mentioning that I need to supply an API key but there is not option in the application to save my API key.
![image](https://github.com/february-labs/devgpt-releases/assets/91850717/b503fbdc-c888-4c5d-a14c-9c1137c99a31)

**Comment by HRA42** [comment]
Hi @PsychosisMNY 🙂

Thank you for reporting this issue to us!
We had some reports on Discord too.

Please check this:

1. You've manually installed version 1.1.0 from the downloads https://www.devgpt.com/download

2. You are pointing at a repo in the settings that you have on your local machine

3. You aren't trying to use a repo that has a really high file count (+100,000). Even if the file count isn't high, please try a different repo - we've had a lot of reports of some repos not functioning correctly.

4. You've restarted the app, and signed out and signed back in.

5. You don't have an extremely long context that may confuse the AI

Please let us know if the issue still persists 🙂

**Comment by PsychosisMNY** [comment]
I guess logging out and in solved this.

Another thing, Sync changes to local doesn't seem to be working.
