### ISSUE TITLE
Issue: Code gen sometimes has difficulty dealing with existing comments and interacts oddly with formatting on large files that it has to make small changes to.

### ISSUE THREAD

**Issue by tom-lewis-code** [february-labs/devgpt-releases#7]
Reported specifically by Andy Brandt.

Issue reported in Python, on a large file that was receiving a small change.

**Comment by andybrandt** [comment]
Code before can be [seen here](https://github.com/andybrandt/DXClusterMonitor/blob/be3d9ca93addd6f2b20c6a91538f2349e640b929/dx_presenter.py).

Code after is pasted below.

`import sys
from datetime import datetime
from PyQt5.QtWidgets import QApplication, QMainWindow, QTableWidget, QTableWidgetItem, QSizePolicy
from PyQt5.QtWidgets import QVBoxLayout, QWidget, QPushButton, QHBoxLayout, QLabel, QSpacerItem
from PyQt5.QtWidgets import QAbstractItemView
from PyQt5.QtCore import Qt, QSortFilterProxyModel, QDateTime, QTimer
from PyQt5.QtGui import QStandardItemModel, QStandardItem, QFont
import dx_settings

show_hf = True
show_vhf = True

def create_table_widget(columns):
    table_widget = QTableWidget(0, len(columns))
    table_widget.setHorizontalHeaderLabels(columns)
    table_widget.horizontalHeader().setStretchLastSection(True)
    table_widget.setEditTriggers(QAbstractItemView.NoEditTriggers)
    return table_widget
def insert_spot_into_table(table_widget, spot):
    row_position = 0
    table_widget.insertRow(row_position)
    data = [
        spot.dx_call,
        f"{spot.frequency:.1f} kHz",
        spot.spotter,
        spot.timestamp.strftime("%H:%M %Y-%m-%d"),
        spot.comment,
        "◉" if spot.lotw else "",
        "◉" if spot.eqsl else "",
        spot.continent,
        f"{spot.band}m" if spot.band is not None else "-",
        spot.mode,
        spot.country,
        spot.adif,
    ]
    for i, value in enumerate(data):
        table_item = QTableWidgetItem(value)
        if i == 0:
            font = table_item.font()
            font.setWeight(QFont.Bold)
            table_item.setFont(font)
            table_item.setTextAlignment(Qt.AlignCenter | Qt.AlignVCenter)
        if i == 1:
            table_item.setTextAlignment(Qt.AlignRight | Qt.AlignVCenter)
        if i == 2:
            table_item.setTextAlignment(Qt.AlignCenter | Qt.AlignVCenter)
        table_widget.setItem(row_position, i, table_item)
def display_new_spots(new_spots):
    global table_widget
    for spot in new_spots:
        if (show_hf and spot.frequency < 60000.0) or (show_vhf and spot.frequency >= 60000.0):
            insert_spot_into_table(table_widget, spot)
        while table_widget.rowCount() > dx_settings.max_spots:
            last_row = table_widget.rowCount() - 1
            table_widget.removeRow(last_row)
def update_spot_details(spot):
    global table_widget
    if dx_settings.debugging_messages: print(f"Presenter: updated spot details for {spot}")
    for row in range(table_widget.rowCount()):
        dx_call_item = table_widget.item(row, 0)
        spotter_item = table_widget.item(row, 2)
        timestamp_item = table_widget.item(row, 3)
        if (dx_call_item and dx_call_item.text() == spot.dx_call and
                spotter_item and spotter_item.text() == spot.spotter and
                timestamp_item and timestamp_item.text() == spot.timestamp.strftime("%H:%M %Y-%m-%d")):
            data = [
                "◉" if spot.lotw else "",
                "◉" if spot.eqsl else "",
                spot.continent,
                f"{spot.band}m" if spot.band is not None else "-",
                spot.mode,
                spot.country,
                spot.adif,
            ]
            for i, value in enumerate(data, start=5):
                table_item = QTableWidgetItem(value)
                table_widget.setItem(row, i, table_item)
            break
def hfvhf_button_clicked(button_clicked, other_button):
    global show_hf, show_vhf
    if button_clicked.text() == "HF":
        if show_hf and not show_vhf:
            show_vhf = True
            show_hf = False
            other_button.setStyleSheet("background-color: green" if show_vhf else "background-color: lightgray")
        else:
            show_hf = not show_hf
        button_clicked.setStyleSheet("background-color: green" if show_hf else "background-color: lightgray")
    elif button_clicked.text() == "VHF":
        if show_vhf and not show_hf:
            show_hf = True
            show_vhf = False
            other_button.setStyleSheet("background-color: green" if show_hf else "background-color: lightgray")
        else:
            show_vhf = not show_vhf
        button_clicked.setStyleSheet("background-color: green" if show_vhf else "background-color: lightgray")
    if dx_settings.debugging_messages: print(f"show_hf: {show_hf}, show_vhf: {show_vhf}")
def create_gui(dx_monitoring):
    global table_widget
    app = QApplication(sys.argv)
    main_window = QMainWindow()
    main_window.setWindowTitle("DX Cluster Monitor")
    main_window.resize(1230, 600)
    central_widget = QWidget()
    main_window.setCentralWidget(central_widget)
    layout = QVBoxLayout(central_widget)
    columns = [
        "DX Call",
        "Frequency",
        "Spotter",
        "Time (UTC)",
        "Comment",
        "LotW",
        "eQSL",
        "Continent",
        "Band",
        "Mode",
        "Country",
        "ADIF",
    ]
    dx_monitoring.spot_received.connect(display_new_spots)
    dx_monitoring.spot_updated.connect(update_spot_details)
    table_widget = create_table_widget(columns)
    layout.addWidget(table_widget)
    table_widget.setColumnWidth(0, 130)
    table_widget.setColumnWidth(1, 120)
    table_widget.setColumnWidth(2, 130)
    table_widget.setColumnWidth(3, 170)
    table_widget.setColumnWidth(4, 300)
    table_widget.setColumnWidth(5, 40)
    table_widget.setColumnWidth(6, 40)
    table_widget.setColumnWidth(7, 50)
    table_widget.setColumnWidth(8, 40)
    table_widget.setColumnWidth(9, 40)
    table_widget.setColumnWidth(10, 180)
    table_widget.setColumnWidth(11, 50)
    button_bar = QHBoxLayout()
    hf_button = QPushButton("HF")
    hf_button.setStyleSheet("background-color: green")
    button_bar.addWidget(hf_button)
    vhf_button = QPushButton("VHF")
    vhf_button.setStyleSheet("background-color: green")
    hf_button.clicked.connect(lambda: hfvhf_button_clicked(hf_button, vhf_button))
    vhf_button.clicked.connect(lambda: hfvhf_button_clicked(vhf_button, hf_button))
    button_bar.addWidget(vhf_button)
    spacer = QSpacerItem(0, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)
    button_bar.addSpacerItem(spacer)
    quit_button = QPushButton("QUIT")
    quit_button.setStyleSheet("background-color: #FFFF99")
    quit_button.clicked.connect(app.quit)
    button_bar.addWidget(quit_button)
    layout.addLayout(button_bar)
    version_label = QLabel("V:" + dx_settings.version_number + " by SP9AB")
    version_label.setAlignment(Qt.AlignBottom | Qt.AlignRight)
    version_font = QFont()
    version_font.setPointSize(8)
    version_label.setFont(version_font)
    layout.addWidget(version_label)
    main_window.show()
    sys.exit(app.exec_())`

**Comment by andybrandt** [comment]
The prompt was: "Change the color of the "QUIT" button to faded yellow."
![image](https://github.com/february-labs/devgpt-releases/assets/5551980/bbfac9c1-a736-497b-a526-e8e7ef919af9)

**Comment by tom-lewis-code** [comment]
Commenting after closed issue here: Thank you for reporting this Andy! An example of a perfect report.
