### ISSUE TITLE
Task keeps spinning forever (v 1.1.0)

### ISSUE THREAD

**Issue by mykjar** [february-labs/devgpt-releases#82]
Simple task for class refactoring keeps spinning endlessly : 

![image](https://github.com/february-labs/devgpt-releases/assets/32451025/f03c4e08-f207-41f2-9c10-0fccb5955815)

This is incredibly frustrating. Mainly because it is unclear **why** this is taking so long. Is it still processing? Have it timed out? What is happening?

**Comment by HRA42** [comment]
The devs are pushing another update that solves this issue today. We will let you know when its out.

**Comment by mykjar** [comment]
![image](https://github.com/february-labs/devgpt-releases/assets/32451025/40ef32f0-bbf8-4a86-b2c0-82d1c066d5c0)
another one

**Comment by shnkt** [comment]
Its still not working can you guys please look into it.

**Comment by mykjar** [comment]
> The devs are pushing another update that solves this issue today. We will let you know when its out.

Any timeline for this?

**Comment by HRA42** [comment]
> > The devs are pushing another update that solves this issue today. We will let you know when its out.
> 
> Any timeline for this?

The update will come out in a few hours.

**Comment by ash-lewis** [comment]
Hi @mykjar , can you please try this again on v1.1.1 and if this still happens can you make a new GitHub issue with the following information please?

prompt used
error message
version number
OS

Thank you!

**Comment by mykjar** [comment]
> Hi @mykjar , can you please try this again on v1.1.1 and if this still happens can you make a new GitHub issue with the following information please?
> 
> prompt used error message version number OS
> 
> Thank you!

After reelease every single prompt I threw at it - worked today. As difficult as it got - it managed to generate satisfactory code. Thank you!
