### ISSUE TITLE
No Close / Full Screen / Minimize buttons

### ISSUE THREAD

**Issue by ggottemo** [february-labs/devgpt-releases#9]
Windows version doesn't have any of the standard buttons to close the app, toggle windowed / full screen / minimize to task bar. Only ways to close are from right clicking the title bar or the icon in the task bar 
![image](https://github.com/february-labs/devgpt-releases/assets/16184296/aa8303ab-e469-4bc7-9483-a1fb8e5eaf4d)
![image](https://github.com/february-labs/devgpt-releases/assets/16184296/e6eef207-b25b-4aa2-81e5-0db1c85e86ce)

**Comment by tom-lewis-code** [comment]
Thanks for reporting this! Closing due to this being a duplicate, this will be merged in during Friday's release.
